# frozen_string_literal: true

source "https://rubygems.org"

gem "thor", "~> 1.4", ">= 1.4.0"
gem "activesupport"
gem "activemodel"

group :development do
  gem "rubocop-shopify", require: false
end

group :test do
  gem "mocha"
end
